#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

VIRTUALENVWRAPPER_PYTHON="/usr/local/bin/python"

export CC=clang
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Work
#source /usr/local/bin/virtualenvwrapper.sh

alias t1="telemetry redis://qBEIXyJ3yq.nKeDaiYw@10.1.1.2"

export GOPATH=$HOME/Work/threatgrid-ops:$HOME/Work/sandcastle

unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help


# Aliases
alias swift=/usr/local/bin/swift

# CDPATH
CDPATH="$HOME/Work:$HOME"

